"""AgentTwin Enterprise domain model (Phase 0–9).

This package is additive. It does not replace Harbor jobs, Playground, or the
existing 1,290-dimension persona YAML schema. Enterprise fields are optional
simulation parameters — not a claim of psychological equivalence to humans.

Public surface: typed IDs, core entities, policy enums and gateway, tenant-bound
repositories (in-memory default, SQLite optional), ``/api/v1``, org-graph
edges, a population-shape builder, experiment launch records mapped onto
Harbor job YAML (not a replacement for ``harbor.Job``), a
provider-independent model gateway beside LiteLLM, control / data /
execution planes with a local sandbox worker, telemetry / evaluation
(synthetic outputs are not human research), a Playground-hosted
enterprise console (nav + experiment wizard + artifact views), and
executive reports (JSON / CSV / PDF-ready HTML) that always carry
limitations plus recommended human validation, and Phase 9 IAM
hardening (OIDC patterns, RBAC+ABAC, append-only audit, CSRF,
rate limits, governance reviews).
"""

from matraix.enterprise.entities import (
    DataClassification,
    Department,
    EnterpriseDimensions,
    EnterprisePersona,
    ExecutionBudget,
    EnterpriseExperiment,
    Experiment,
    ExperimentGovernance,
    ExperimentKind,
    Organization,
    Population,
    Team,
    Tenant,
)
from matraix.enterprise.errors import (
    AppendOnlyAuditError,
    ApprovalRequiredError,
    AuthorizationError,
    CrossTenantAccessError,
    EnterpriseSchemaError,
    EntityNotFoundError,
    PolicyDeniedError,
    WorkerNotAvailableError,
)
from matraix.enterprise.graph import OrgEdge, OrgNodeKind, OrgRelation
from matraix.enterprise.ids import (
    ArtifactId,
    CohortId,
    DepartmentId,
    EntityId,
    EventId,
    ExecutionId,
    ExperimentId,
    ModelId,
    ObservationId,
    OrganizationId,
    OrgEdgeId,
    PersonaId,
    PolicyId,
    PopulationId,
    ScenarioId,
    TaskId,
    TeamId,
    TenantId,
    UserId,
    new_id,
)
from matraix.enterprise.experiment_launch import (
    CostEstimate,
    estimate_experiment_cost,
    map_experiment_to_harbor_job,
)
from matraix.enterprise.model_gateway import (
    DEFAULT_MODEL_CATALOG,
    ModelCapabilities,
    ModelGateway,
    ModelPolicy,
    ModelProvider,
    ModelRequest,
    ModelResponse,
    ModelRoute,
    ModelUsage,
    catalog_for_policy,
    complete_model,
    default_model_policy,
    resolve_model_policy,
    route_model,
)
from matraix.enterprise.population_builder import (
    GenerationBackend,
    PopulationDeclaration,
    PopulationSegment,
    build_population_declaration,
)
from matraix.enterprise.policy import (
    PolicyDecision,
    PolicyEvaluation,
    PolicyRequest,
    default_simulation_decision,
    evaluate_policy,
)
from matraix.enterprise.repositories import (
    EnterpriseRepository,
    EnterpriseStore,
    InMemoryEnterpriseStore,
)
from matraix.enterprise.sqlite_store import SqliteEnterpriseStore
from matraix.enterprise.events import (
    EventBus,
    EventKind,
    EnterpriseEvent,
    SimulationClock,
    WorldState,
)
from matraix.enterprise.runtime import (
    Artifact,
    ControlPlane,
    DataPlane,
    EnterpriseRuntime,
    ExecutionPlane,
    ExecutionRecord,
    ExecutionStatus,
    PlaneName,
    WorkRequest,
    WorkerKind,
    get_worker,
    worker_catalog,
)
from matraix.enterprise.evaluation import (
    EvaluationBundle,
    EvaluationResult,
    EvaluatorKind,
    evaluate_execution,
    supplemental_llm_judge,
)
from matraix.enterprise.metrics import (
    AggregatedMetric,
    MetricLevel,
    MetricPoint,
    MetricsRegistry,
    SYNTHETIC_METRIC_LIMITATION,
)
from matraix.enterprise.console import CONSOLE_NAV, WIZARD_STEPS, console_manifest
from matraix.enterprise.observability import record_execution_observability
from matraix.enterprise.reporting import (
    SCHEMA_VERSION as EXECUTIVE_REPORT_SCHEMA,
    ExecutiveReport,
    REQUIRED_LIMITATIONS,
    build_executive_report,
    format_report_csv,
    format_report_html,
    format_report_json,
    render_report,
    report_from_runtime,
)
from matraix.enterprise.telemetry import (
    FAILURE_CLASSES,
    FailureClass,
    FailureRecord,
    InMemoryTracer,
    SpanRecord,
    classify_failure,
    common_attributes,
    new_trace_id,
)
from matraix.enterprise.store import (
    create_tenant_with_default_org,
    open_enterprise_store,
)
from matraix.enterprise.audit import AuditEvent, new_audit_event
from matraix.enterprise.authz import authorize, permission_for
from matraix.enterprise.governance import GovernanceReview, ReviewKind, ReviewStatus
from matraix.enterprise.identity import (
    ANONYMOUS,
    EnterpriseUser,
    Permission,
    Principal,
    Role,
    permissions_for,
)
from matraix.enterprise.oidc import mint_dev_jwt, oidc_metadata, principal_from_claims

__all__ = [
    "ANONYMOUS",
    "AppendOnlyAuditError",
    "ApprovalRequiredError",
    "AuditEvent",
    "AuthorizationError",
    "Artifact",
    "ArtifactId",
    "CohortId",
    "ControlPlane",
    "CrossTenantAccessError",
    "DataClassification",
    "DataPlane",
    "DEFAULT_MODEL_CATALOG",
    "Department",
    "DepartmentId",
    "CostEstimate",
    "EnterpriseDimensions",
    "EnterpriseEvent",
    "EnterpriseExperiment",
    "EnterprisePersona",
    "EnterpriseRuntime",
    "EnterpriseSchemaError",
    "EnterpriseRepository",
    "EnterpriseStore",
    "EntityId",
    "EntityNotFoundError",
    "estimate_experiment_cost",
    "evaluate_execution",
    "evaluate_policy",
    "ExecutiveReport",
    "EXECUTIVE_REPORT_SCHEMA",
    "EvaluationBundle",
    "EvaluationResult",
    "EvaluatorKind",
    "FAILURE_CLASSES",
    "FailureClass",
    "FailureRecord",
    "EventBus",
    "EventId",
    "EventKind",
    "ExecutionBudget",
    "ExecutionId",
    "ExecutionPlane",
    "ExecutionRecord",
    "ExecutionStatus",
    "Experiment",
    "ExperimentGovernance",
    "ExperimentId",
    "ExperimentKind",
    "GenerationBackend",
    "get_worker",
    "InMemoryEnterpriseStore",
    "InMemoryTracer",
    "classify_failure",
    "common_attributes",
    "MetricLevel",
    "MetricPoint",
    "MetricsRegistry",
    "AggregatedMetric",
    "record_execution_observability",
    "render_report",
    "report_from_runtime",
    "REQUIRED_LIMITATIONS",
    "authorize",
    "EnterpriseUser",
    "GovernanceReview",
    "mint_dev_jwt",
    "new_audit_event",
    "oidc_metadata",
    "Permission",
    "permission_for",
    "permissions_for",
    "Principal",
    "principal_from_claims",
    "ReviewKind",
    "ReviewStatus",
    "Role",
    "build_executive_report",
    "format_report_csv",
    "format_report_html",
    "format_report_json",
    "supplemental_llm_judge",
    "SYNTHETIC_METRIC_LIMITATION",
    "SpanRecord",
    "new_trace_id",
    "map_experiment_to_harbor_job",
    "ModelCapabilities",
    "ModelGateway",
    "ModelId",
    "ModelPolicy",
    "ModelProvider",
    "ModelRequest",
    "ModelResponse",
    "ModelRoute",
    "ModelUsage",
    "ObservationId",
    "open_enterprise_store",
    "OrgEdge",
    "OrgEdgeId",
    "OrgNodeKind",
    "OrgRelation",
    "Organization",
    "OrganizationId",
    "PersonaId",
    "PlaneName",
    "PolicyDecision",
    "PolicyDeniedError",
    "PolicyEvaluation",
    "PolicyId",
    "PolicyRequest",
    "Population",
    "PopulationDeclaration",
    "PopulationId",
    "PopulationSegment",
    "build_population_declaration",
    "catalog_for_policy",
    "complete_model",
    "CONSOLE_NAV",
    "console_manifest",
    "create_tenant_with_default_org",
    "default_model_policy",
    "default_simulation_decision",
    "resolve_model_policy",
    "route_model",
    "ScenarioId",
    "SimulationClock",
    "SqliteEnterpriseStore",
    "TaskId",
    "Team",
    "TeamId",
    "Tenant",
    "TenantId",
    "UserId",
    "worker_catalog",
    "WIZARD_STEPS",
    "WorkerKind",
    "WorkerNotAvailableError",
    "WorkRequest",
    "WorldState",
    "new_id",
]
